### ISSUE TITLE
`--ginkgo.progress` is deprecated

### ISSUE THREAD

**Issue by cPu1** [eksctl-io/eksctl#6936] opened 2023-08-10 07:13 UTC
The integration test runner passes `--progress` to `ginkgo` but that option is deprecated. 

```
--ginkgo.progress is deprecated .  The functionality provided by --progress was confusing and is no longer needed.  Use --show-node-events instead to see node entry and exit events included in the timeline of failed and verbose specs.  Or you can run with -vv to always see all node events.  Lastly, --poll-progress-after and the PollProgressAfter decorator now provide a better mechanism for debugging specs that tend to get stuck.
```

The test runner should replace that option with `--show-node-events` or `-vv`.

**Comment by Himangini** [comment] 2023-08-11 12:42
Dupe of https://github.com/eksctl-io/eksctl-ci/issues/67 :D

**Comment by Himangini** [comment] 2023-08-16 11:19
closing this in favor of the older issue

**Closed by Himangini** 2023-08-16 11:19 UTC
Labels: area/tech-debt, area/ci
